#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
export CONFIG_DIR="$HOME/.config/sketchybar"

FONT="SF Pro"
PADDINGS=5
SHADOW=on

sketchybar --bar     height=36                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=top                                      \
                     topmost=window                                    \
                     sticky=on                                         \
                     padding_right=12                                  \
                     padding_left=12                                   \
                     blur_radius=0                                     \
                     notch_width=0                                     \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:13.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left side
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/aerospace.sh"

# Right side
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/media.sh"
source "$ITEM_DIR/pomodoro.sh"
source "$ITEM_DIR/cpu_mem.sh"
source "$ITEM_DIR/privacy.sh"
source "$ITEM_DIR/battery.sh"

sketchybar --update

echo "sketchybar configuration loaded.."
